# Use the latest official Node.js 20 image with a Puppeteer-compatible SHA
FROM node:20@sha256:fffa89e023a3351904c04284029105d9e2ac7020886d683775a298569591e5bb

# Configure default locale (important for chrome-headless-shell).
ENV LANG en_US.UTF-8

# Install necessary fonts and dbus for character set support and Chrome dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros \
    fonts-kacst fonts-freefont-ttf dbus dbus-x11 \
    && rm -rf /var/lib/apt/lists/*

# Add pptruser to run Chrome as a non-privileged user
RUN groupadd -r pptruser && useradd -u 10042 -rm -g pptruser -G audio,video pptruser

USER pptruser
WORKDIR /home/pptruser

# Copy Puppeteer dependencies (latest version)
COPY puppeteer-browsers-latest.tgz puppeteer-latest.tgz puppeteer-core-latest.tgz ./

# Set DBus address
ENV DBUS_SESSION_BUS_ADDRESS autolaunch:

# Install Puppeteer packages
RUN npm install ./puppeteer-browsers-latest.tgz ./puppeteer-core-latest.tgz ./puppeteer-latest.tgz \
    && rm ./puppeteer-browsers-latest.tgz ./puppeteer-core-latest.tgz ./puppeteer-latest.tgz

# Switch to root to install Puppeteer Chrome dependencies
USER root
RUN npx puppeteer browsers install chrome --install-deps

# Return to pptruser for security
USER pptruser

# Set up the working directory for your app
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy the rest of the application code
COPY . .

# Set the command to start the application
CMD ["node", "begin.js"]
